streamify:
  outputs:
    local:
      type: duckdb
      path: "../{{ env_var('STREAMIFY_DUCKDB_PATH', 'data/streamify.duckdb') }}"
      threads: "{{ env_var('DBT_THREADS', 1) | int }}"
  target: local
