with source as (
    select *
    from read_json_auto('../{{ env_var("STREAMIFY_RAW_DIR", "data/raw/yamusic") }}/_manifest.json')
)

select
    cast(source as varchar) as manifest_source,
    cast(generated_at as timestamp) as manifest_generated_at,
    cast(raw_dir as varchar) as manifest_raw_dir,
    coalesce(cast(json_only as boolean), false) as manifest_json_only,
    cast(adapter.adapter_name as varchar) as adapter_name,
    cast(adapter.adapter_version as varchar) as adapter_version,
    cast(adapter.client_library as varchar) as client_library,
    cast(adapter.client_library_version as varchar) as client_library_version,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_shortcuts_seen') as bigint), 0) as diagnostic_liked_shortcuts_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_tracks_written') as bigint), 0) as diagnostic_liked_tracks_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_shortcuts_fetch_failed') as bigint), 0) as diagnostic_liked_shortcuts_fetch_failed,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_shortcuts_missing_track_id') as bigint), 0) as diagnostic_liked_shortcuts_missing_track_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_tracks_duplicate_skipped') as bigint), 0) as diagnostic_liked_tracks_duplicate_skipped,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_albums_seen') as bigint), 0) as diagnostic_liked_albums_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_albums_written') as bigint), 0) as diagnostic_liked_albums_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_albums_missing_id') as bigint), 0) as diagnostic_liked_albums_missing_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_albums_duplicate_skipped') as bigint), 0) as diagnostic_liked_albums_duplicate_skipped,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_artists_seen') as bigint), 0) as diagnostic_liked_artists_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_artists_written') as bigint), 0) as diagnostic_liked_artists_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_artists_missing_id') as bigint), 0) as diagnostic_liked_artists_missing_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_artists_duplicate_skipped') as bigint), 0) as diagnostic_liked_artists_duplicate_skipped,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_playlists_seen') as bigint), 0) as diagnostic_liked_playlists_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_playlists_written') as bigint), 0) as diagnostic_liked_playlists_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_playlists_missing_id') as bigint), 0) as diagnostic_liked_playlists_missing_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.liked_playlists_duplicate_skipped') as bigint), 0) as diagnostic_liked_playlists_duplicate_skipped,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlists_seen') as bigint), 0) as diagnostic_playlists_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlists_written') as bigint), 0) as diagnostic_playlists_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlists_missing_id') as bigint), 0) as diagnostic_playlists_missing_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_fetch_fallbacks') as bigint), 0) as diagnostic_playlist_fetch_fallbacks,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_tracks_seen') as bigint), 0) as diagnostic_playlist_tracks_seen,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_tracks_written') as bigint), 0) as diagnostic_playlist_tracks_written,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_tracks_fetch_failed') as bigint), 0) as diagnostic_playlist_tracks_fetch_failed,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_tracks_missing_track_id') as bigint), 0) as diagnostic_playlist_tracks_missing_track_id,
    coalesce(cast(json_extract_string(to_json(diagnostics), '$.playlist_tracks_duplicate_skipped') as bigint), 0) as diagnostic_playlist_tracks_duplicate_skipped,
    coalesce(cast(datasets.tracks.row_count as bigint), 0) as raw_tracks,
    cast(datasets.tracks.jsonl_sha256 as varchar) as raw_tracks_sha256,
    coalesce(cast(datasets.artists.row_count as bigint), 0) as raw_artists,
    cast(datasets.artists.jsonl_sha256 as varchar) as raw_artists_sha256,
    coalesce(cast(datasets.albums.row_count as bigint), 0) as raw_albums,
    cast(datasets.albums.jsonl_sha256 as varchar) as raw_albums_sha256,
    coalesce(cast(datasets.playlists.row_count as bigint), 0) as raw_playlists,
    cast(datasets.playlists.jsonl_sha256 as varchar) as raw_playlists_sha256,
    coalesce(cast(datasets.playlist_tracks.row_count as bigint), 0) as raw_playlist_tracks,
    cast(datasets.playlist_tracks.jsonl_sha256 as varchar) as raw_playlist_tracks_sha256,
    coalesce(cast(datasets.user_library_events.row_count as bigint), 0) as raw_user_library_events,
    cast(datasets.user_library_events.jsonl_sha256 as varchar) as raw_user_library_events_sha256
from source
